steps:
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - kms
    - decrypt
    - "--location=asia-northeast1"
    - "--keyring=config"
    - "--key=snskey"
    - "--plaintext-file=.env"
    - "--ciphertext-file=.env.enc"
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "1600s"
timeout: "1600s"